/** Maps tool names to BrowserTools method names used by executeTool. */
export const TOOL_HANDLER_REGISTRY: Record<string, string> = {
  navigate: 'navigate',
  openTab: 'openTab',
  click: 'click',
  hover: 'hover',
  mouse: 'mouse',
  type: 'type',
  pressKey: 'pressKey',
  scroll: 'scroll',
  getContent: 'getContent',
  screenshot: 'screenshot',
  annotatedScreenshot: 'annotatedScreenshot',
  elementScreenshot: 'elementScreenshot',
  getTabs: 'getTabs',
  closeTab: 'closeTab',
  switchTab: 'focusTab',
  focusTab: 'focusTab',
  groupTabs: 'groupTabs',
  executeScript: 'executeScript',
  httpRequest: 'httpRequest',
  getNetworkRequests: 'getNetworkRequests',
  findElement: 'findElement',
  readPage: 'readPage',
  wait: 'wait',
  dismissModal: 'dismissModal',
  clipboard: 'clipboard',
  setInputFiles: 'setInputFiles',
  selectOption: 'selectOption',
  fillForm: 'fillForm',
  navigateHistory: 'navigateHistory',
  highlightElement: 'highlightElement',
  captureDownload: 'captureDownload',
  findInPage: 'findInPage',
  extractTable: 'extractTable',
  harvestScroll: 'harvestScroll',
  getStorageData: 'getStorageData',
  getPerformanceMetrics: 'getPerformanceMetrics',
  getConsoleOutput: 'getConsoleOutput',
  cdp: 'cdp',
};

/** Tools handled inline in executeTool rather than via a class method. */
export const INLINE_TOOL_HANDLERS = new Set(['describeSessionTabs']);
